### ISSUE TITLE
TRK instead of HDG

### ISSUE THREAD

**Issue by zazaboeing** [mihai-dinculescu/msfs-2020-gps-link#2]
Hi! Great plugin, works phenomenal, but can you please make ir show TRK (over ground) instead of the Heading of the airplane, like a true GPS would? THANKS!!

**Comment by mihai-dinculescu** [comment]
Thanks for reporting this.

Version 0.2.1 changes it from `PLANE HEADING DEGREES TRUE` to `GPS GROUND TRUE TRACK`.

http://www.prepar3d.com/SDKv3/LearningCenter/utilities/variables/simulation_variables.html#Simulation%20Variables also lists
- `GPS GROUND TRUE HEADING`
- `GPS GROUND MAGNETIC TRACK`

but I guess that `GPS GROUND TRUE TRACK` is the most appropriate one?

Would there be any value in allowing the user which one to use?

**Comment by zazaboeing** [comment]
Thanks for the reply mihai!

The correct is GPS GROUND MAGNETIC TRACK.

**Comment by mihai-dinculescu** [comment]
Can you please explain your reasoning? Or point me to some documentation? I'd love to find out more.

**Comment by zazaboeing** [comment]
Hi Mihai! The reason is no GPS or any other navigation device in an airplane use TRUE orientation for anything, GPS specially uses Magnetic TRK which is what we need to know to navigate anywhere. The Bearing of the GPS, the DTK of a waypoint, everything is MAGNETIC and we use Magnetic TRK to TRACK these two.

You would only use TRUE navigation where the magnetic declination changes VERY much, and this is approaching (really near) the Magnetic Poles. Only some big airliners that navigate through the poles uses this feature. 

Source: Myself being an airline pilot for 20+ years.  And you could find thousands of docs online explaining this. 

Thanks for your job! And most of all, keeping it free for the community!

**Comment by mihai-dinculescu** [comment]
Thank you for the explanation!

Version 0.2.2 changes it from `GPS GROUND TRUE TRACK` to `GPS GROUND MAGNETIC TRACK`.

Yep, this project will definitely stay free forever :)

**Comment by zazaboeing** [comment]
Hi Mihai! Testing it now, the data sent for the GPS is the correct magnetic track, but somehow with **ADDED MAGVAR**!!
Example, flying over SBGO in Brazil, where the magnetic variation is +21 degrees (W) on a heading of 230 without any wind, shows a TRK of 251 where it should show 230 (HDG=TRK when there's no wind).
If you could program that data to show the GPS GROUND MAGNETIC TRACK minus MAGVAR, for a test, it would be nice. This is really intriguing.

**Comment by mihai-dinculescu** [comment]
It's done. I'm sorry it took so long.

Version 0.2.3 changes it from `GPS GROUND MAGNETIC TRACK` to `GPS GROUND MAGNETIC TRACK` - `MAGVAR`.

Please let me know how you find it.
