### ISSUE TITLE
GPS speed correction

### ISSUE THREAD

**Issue by PavelFilippovich** [mihai-dinculescu/msfs-2020-gps-link#34]
Hello! The program is excellent! Flying began to look very different with Jeppesen Flitedeсk.
Only the speed is transmitted with an error. Therefore, Flitedeck displays it incorrectly and does not calculate the travel time correctly.
Could you fix this?

![2022-11-13_10-46-26](https://user-images.githubusercontent.com/116830995/201524548-bbaa6dbb-1672-4803-a3d7-4808bbb835ad.png)

![2022-11-13_10-45-59](https://user-images.githubusercontent.com/116830995/201524677-d9b34136-778b-4ab5-a9ed-6d35759db21d.png)

**Comment by PavelFilippovich** [comment]
I will assume that you are transmitting the speed in knots, but the GPS should transmit the speed in meters per second.
151.8 m/s = 295.08 knots
It matches the screenshots well.

**Comment by PavelFilippovich** [comment]
I will assume that you are transmitting the speed in meters per second, but the GPS should transmit the speed in knots.
151.8 m/s = 295.08 knots
It matches the screenshots well.

**Comment by mihai-dinculescu** [comment]
Thank you for the bug report, @PavelFilippovich .

You are correct, the issue was that the ground speed was sent in meters per second instead of knots.

This has been fixed in v0.3.1.

**Comment by PavelFilippovich** [comment]
Wow! Everything works right!
