### ISSUE TITLE
Cannot select Com Port

### ISSUE THREAD

**Issue by bam2000** [mihai-dinculescu/msfs-2020-gps-link#74]
Hi, i followed the instructions on the Com0Com and created 2 Com ports witht he software, i can also select the Ports in my Client software (FliteDeck) but i'm unable to select the Ports in your application, they dont want to show up. What can i do?
Thanks

**Comment by mihai-dinculescu** [comment]
You did restart MSFS 2020 GPS Link after you installed and configured Com0Com, right?

Did you configure Com0Com via the console or the UI?

If via the console, please run `list` and paste the output.
If via the UI, please post a screenshot.

**Comment by bam2000** [comment]
Hi, thanks for the fast reply. Yes tried restarting the app and even windows.
<a href="https://www.directupload.net" target="_blank"><img src="https://s20.directupload.net/images/230803/mij9ryom.png" title="Kostenlos Bilder und Fotos hochladen"></a>

Tried even rename the Port Names to COM3 and COM4. as i said the other Program detects the Ports :(

**Comment by bam2000** [comment]
Little Update in Case that matters. I Had to use the Old version of com0com, instead of 3.0 i had to install 2.2.2 because the newer one doesn't work under WIndows 10 with the signature drivers, they still get disabled in Device Manager for not beeing the correct signature. Does it matter ? because you cant use them with Secureboot and newer systems.

**Comment by bam2000** [comment]
Edit found the solution. Had to install a signed Version of Com0Com 3.0 and followed again your guide.
Link to the working installation: http://radio.jsh.de/com0com.zip

**Comment by mihai-dinculescu** [comment]
Thank you very much for the updates. I'll make a note to update the documentation based on what you've found.

**Comment by mihai-dinculescu** [comment]
Just to double-check, did you try the signed version found here, and it didn't work for you?
https://sourceforge.net/projects/com0com/files/com0com/3.0.0.0/

**Comment by bam2000** [comment]
> Just to double-check, did you try the signed version found here, and it didn't work for you? https://sourceforge.net/projects/com0com/files/com0com/3.0.0.0/

Yes exactly that one doesn't work for anything >Win7 ... even though it says its signed drivers i could not get them to work. More info about that issue: https://pete.akeo.ie/2011/07/com0com-signed-drivers.html
