### ISSUE TITLE
Cant Connect to Port

### ISSUE THREAD

**Issue by TornadoKegan** [mihai-dinculescu/msfs-2020-gps-link#80]
I am trying to connect to a port. I am trying to connect to my phone but it is not working, it is not connecting. just hoping i can resolve

**Comment by mihai-dinculescu** [comment]
What navigation app are you trying to use?

**Comment by TornadoKegan** [comment]
google maps. android

**Comment by TornadoKegan** [comment]
nevermind figured it out
